### ISSUE TITLE
MSPaint easter eggs and lesser known features

### ISSUE THREAD

**Issue by pachuco** [katahiromz/RPaint#1]
Original MSPaint has some nifty and not so obvious behaviours. Maybe they can make their way into RPaint(as-is or refined).

- the zoom has a 10x level. You have to click pixel perfect at bottom of zoom selector. Or can cheat and lengthen the zoom selector to have more area to click(windowspy or hexedit exe).

- Shift + (L or R)Click + Drag has meanings depending on context.
  - With a pencil/brush, it locks drawing in straight line(hor, vert, diag).
  - With line, it does same locking, except you can rotate it in 45deg angles.
  - With selection, it stamps that selection down like a brush.
  - Eraser R click(colour mask eraser) already implemented.

- Ctrl + NumPlus/NumMinus changes the size of brush, including those that don't have size option.
  - Makes pencil/brush nib smaller or bigger.
  - Resizes selection by 2x or 0.5x.
  - Plays poorly with undo.

- There's probably more, but I forgets.

**Comment by katahiromz** [comment]
Thanks for contribution.

> You have to click pixel perfect at bottom of zoom selector.

The zoom fix goes #2.

> With a pencil/brush, it locks drawing in straight line(hor, vert, diag).

Confirmed. Not implemented yet.

> With line, it does same locking, except you can rotate it in 45deg angles.

Confirmed. Already implemented.

> With selection, it stamps that selection down like a brush.

Confirmed. Not implemented yet. Shift and Ctrl have different behaviour.

> Makes pencil/brush nib smaller or bigger.

Confirmed. Not implemented yet.

> Resizes selection by 2x or 0.5x.

Confirmed. Not implemented yet.

> Plays poorly with undo.

I can't understand the meaning.

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5717

**Comment by pachuco** [comment]
> I can't understand meaning.

In MSPaint, when undoing strokes done with tool zoomed by Ctrl + Plus/Minus, the undo may leave garbage pixels behind.

**Comment by katahiromz** [comment]
I don't want to show garbage without meaning.

**Comment by pachuco** [comment]
Good!

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5726

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5734

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5738

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5739

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5740

**Comment by katahiromz** [comment]
Fixed. Closed. Thank you very much!
