### ISSUE TITLE
Problems with painting scrollbars and calculating the size of the image (?) under Windows10

### ISSUE THREAD

**Issue by JacekLub** [katahiromz/RPaint#3]
Problem show themselves as:
1) 'view inheritance' - newly opened images inherit the position in the image area being shown and the postion of scrollbars fron the previously opened image, this result in glitches as unnecessary scrollbars in small images which fit the program window's size, or unnecessary scrollbars+new image scrolled out of the program's window;
2) 'missing scrollbars' in large images (perhaps it's another instance of 'view inheritance', when a larger image is opened after a smaller image) - an image which exceeds the size of the program window is initially displayed without scrollbars; the appear only upon resizing the program window, scrolling the image with the mouse wheel or repainting the window when it gets covered by anothe one;
3) "file .. cannot be loaded' message - if you opened an image with 'missing toolbars' effect and resized the window, scrolled the image so that the toolbars appeared, and then you try to open another larger image, you may get a message "file ... cannot be loaded", this happens with some images, it seems that with large ones, like 7600x6500px.
They seem interrelated, seems like some inconsistences in the messaging mechanism or GUI behaviour between Win and ROS and not mspaint itself.
VIEWS OF THE GLITCHES:

![01a_ms_paint_on_Win10_view_inheritance_unnecessary_scrollbars_shown](https://github.com/katahiromz/RPaint/assets/97013950/7103171c-e56b-45f1-8032-69c4e8ca6424)

![02_mspaint_on_Win10_missing_scrollbars_on_large_image](https://github.com/katahiromz/RPaint/assets/97013950/d5b662e8-0993-4a76-b013-10833f25b735)

![03_mspaint_on_Win10_file_cannont_be_loaded](https://github.com/katahiromz/RPaint/assets/97013950/423c5639-895e-4df3-a57f-d2dc259eb10e)

![01b_mspaint_on_Win10_view_inheritance_new image scrolled out of the window](https://github.com/katahiromz/RPaint/assets/97013950/0e6f8c10-30eb-4484-9d28-4f2ca6d23420)

**Comment by JacekLub** [comment]
Pls try the enclosed image files; 
with them, I have the 'file .. cannot be loaded' bug occurance guaranteed:
![LTO-38B1_(250K)_Humason_DMA_ed2_March1974_300dpi](https://github.com/katahiromz/RPaint/assets/97013950/1441ade9-f409-40b4-ab22-d058eae3b695)
![LTO-38B3_(250K)_Freud_DMA_ed2_February1974_300dpi](https://github.com/katahiromz/RPaint/assets/97013950/37142822-b7fb-472f-abd2-f205f1e140c1)
![LTO-38B4_(250K)_Zinner_DMA_ed2_February1974_300dpi](https://github.com/katahiromz/RPaint/assets/97013950/fcb6511f-5847-4273-bddf-1cf3a82b27e5)
![LTO-39A4_(250K)_Vaisala_DMA_ed2_March1974_300dpi](https://github.com/katahiromz/RPaint/assets/97013950/05a83962-dc24-4f5e-bb03-020a9ad60fb1)
![LTO-39B1_(250K)_Federov_DMA_ed1_March1974_300dpi](https://github.com/katahiromz/RPaint/assets/97013950/33b246a9-00d4-428d-9cf9-0a91fd1c0acb)

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5761

**Comment by katahiromz** [comment]
> 'view inheritance'

Fixed.

> 'missing scrollbars'

Fixed.

**Comment by katahiromz** [comment]
Japanese tranlation:

「ファイル .. ロードできません」メッセージ - 「ツールバーが見つからない」効果のある画像を開いてウィンドウのサイズを変更し、画像をスクロールしてツールバーが表示されてから、別の大きな画像を開こうとすると、メッセージが表示されることがあります。 「ファイル ... を読み込むことができません」、これは一部の画像で発生しますが、7600x6500px などの大きな画像で発生するようです。
これらは相互に関連しているように見えますが、mspaint 自体ではなく、Win と ROS の間のメッセージング メカニズムまたは GUI の動作に矛盾があるようです。

**Comment by katahiromz** [comment]
> it seems that with large ones, like 7600x6500px.

It seems like due to x86 memory limitation. The answer is to use x64 mspaint. Closed.
