### ISSUE TITLE
Few points in mouse capture compared to MSPaint

### ISSUE THREAD

**Issue by pachuco** [katahiromz/RPaint#4]
Drawing in XP MSPaint feels snappier. This is made evident when zooming in and rubbing pencil tool with speed, across canvas.
Two things are seen:
- a perceptible lag between drawing and mouse cursor, as RPaint waits for latest point to complete a line segment.
- coarser lines with fewer segments in RPaint compared to MSPaint.

Methinks that MSPaint samples mouse more often.

**Comment by katahiromz** [comment]
Japanese translation:

XP MSPaint での描画はよりきびきびと感じられます。 これは、ズームインして鉛筆ツールをキャンバス上で高速でこすると明らかになります。
次の 2 つのことがわかります。

RPaint が線分を完成させるための最新の点を待機するため、描画とマウス カーソルの間に知覚可能な遅れが生じます。
MSPaint と比較して、RPaint では線が粗く、セグメントが少なくなります。
MSPaint はマウスをより頻繁にサンプリングすると思います。

**Comment by katahiromz** [comment]
https://jira.reactos.org/browse/CORE-19237

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/5795

**Comment by katahiromz** [comment]
https://github.com/reactos/reactos/pull/6005

**Comment by katahiromz** [comment]
Should be FIXED now. Closed.
