### ISSUE TITLE
Layers support?

### ISSUE THREAD

**Issue by roytam1** [katahiromz/RPaint#5]
MS Paint in Win11 supports Layers, I wonder if ROS Paint will add layers (for providing a better Paint for ROS/older windows)?

and there is some more features in post-XP/Vista Paint that may worth providing in ROS Paint:

- Shapes
- Brushes
- Crop canvas to selection size

**Comment by katahiromz** [comment]
Layers and Ribbon are in low priority. There are still major bugs. Postponed.

**Comment by roytam1** [comment]
> Ribbon

ah no, I'm not talking about Ribbon UI. Those functions can still be implemented without Ribbon UI.

**Comment by katahiromz** [comment]
Trimming is useful. I will implement.

**Comment by katahiromz** [comment]
Fixed.
